#!/usr/bin/env python

import os
import sys
import yaml
import moa.utils
import moa.template

import moa.logger as l


from moa.sysConf import sysConf

from jinja2 import Template as jTemplate

tPluginFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'plugin.rst.jinja2')
tIndexFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'plugin.index.rst.jinja2')

tPlugin = jTemplate(open(tPluginFile).read())
tIndex = jTemplate(open(tIndexFile).read())

all_plugs = []
l.warning("start parsing plugins")
#plugindir = os.path.join(moa.utils.getMoaBase(), 'lib', 'python', 'moa', 'plugin')
#l.warning("in directory %s" % plugindir)

for category in ['job', 'system']:
    for plugin in sysConf.plugins[category].keys():
        plugInfo = sysConf.plugins[category].get(plugin, {})
        module = plugInfo.module
        name = plugin
        print 'Found plugin: ', category, name
        all_plugs.append((category, name))
        with open('%s__%s.rst' % (category, name), 'w') as F:
            F.write(tPlugin.render({'module' : module}))

all_plugs.sort()
with open("index.rst", 'w') as F:
    F.write(tIndex.render({'plugins' : all_plugs}))
