
def show_help():

    print """
######################################################################

## WWWMoaLighty Help ##

You can use WWWMoaLighty like most other interactive command-line
utilities.  WWWMoaLighty actively manages the lighttpd processes
that are currently running.  Therefore, it remains open until all
of those processes have been terminated.

To control WWWMoaLighty while it is running, you can use the
following commands:

Using \"q\", \"quit\", or \"exit\" will terminate WWWMoaLighty. If
any lighttpd instances that were started with WWWMoaLighty are
still running, you will be prompted to terminate them as well.

Using \"h\", \"help\", or \"?\" will display this help message.

Using \"s\" or \"status\" will show the current lighttpd instances
being managed by WWWMoaLighty.

Using \"r\" or \"run\" will allow you to start up a new lighttpd
instance associated with WWWMoa.  You will be prompted about
what parameters to use for the new instance.

Using \"k\" or \"kill\" will allow you to shut down a currently
running lighttpd instance (given that it was started with
WWWMoaLighty).

Using \"l\" or \"log\" will allow you to see recent events that
you might be interested in.  Certain messages generated by
lighttpd will be shown.

######################################################################
"""

