#!/usr/bin/env python
# 
# Copyright 2009-2011, Mark Fiers, Plant & Food Research
# 
# This file is part of Moa - http://github.com/mfiers/Moa
# 
# Licensed under the GPL license (see COPYING)
# 
"""
Update the header with license of any moa related sourcefile
"""

header = """Copyright 2009-2011 Mark Fiers
The New Zealand Institute for Plant & Food Research

This file is part of Moa - http://github.com/mfiers/Moa

Licensed under the GPL license (see 'COPYING')
""".split("\n")

import os
import sys

infile = sys.argv[1]

#read the original source file
F = open(infile, 'r')
source = F.readlines()
F.close()

shebang = ""
if source[0][:2] == '#!':
    shebang = source.pop(0)

#write out the file 
F = open(infile, 'w')

if shebang: F.write(shebang)

prefix = "#"
for h in header:
    F.write("%s %s\n" % (prefix, h))

inoldheader = True
i = 0
for s in source:
    if inoldheader and ((s.find(prefix) == 0) or not s.strip()):
        continue
    elif inoldheader:
        inoldheader = False

    F.write(s)
    
F.close()
        
