#!/usr/bin/env bash
# 
# Copyright 2009-2011, Mark Fiers, Plant & Food Research
# 
# This file is part of Moa - http://github.com/mfiers/Moa
# 
# Moa is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# 
# Moa is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Moa.  If not, see <http://www.gnu.org/licenses/>.
# 
version=$1
from=$2
work=$3

DISTS=karmic

mkdir -p $work || true
cd $from
git archive --format=tar --prefix=moa-$version/ v$version \
    Makefile \
    bin \
    COPYING \
    doc \
    etc \
    lib \
    quick_init.sh \
    README \
    template \
    | gzip > $work/moa-$1.tar.gz

git archive --format=tar --prefix=moa-$version/ v$version \
    debian \
    | gzip > $work/moa-debian-$1.tar.gz

echo "generated source archive in $work/moa-$1.tar.gz"
cd $work
for dist in karmic; do
    rm -rf $dist || true
    mkdir $dist || true
    cd $dist
    cp ../moa-$1.tar.gz moa_$1.orig.tar.gz
    tar xvzf moa_$1.orig.tar.gz
    tar xvzf ../moa-debian-$1.tar.gz
    cat moa-$version/debian/changelog.t | sed "s/DIST/$dist/g" > moa-$version/debian/changelog
    cd moa-$version; 
    dpkg-buildpackage -S -rfakeroot
    cd ..
    lintian -i *dsc
    sudo DIST=$dist pbuilder build *dsc
done