#!/usr/bin/env python
# 
# Copyright 2009-2011, Mark Fiers, Plant & Food Research
# 
# This file is part of Moa - http://github.com/mfiers/Moa
# 
# Moa is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# 
# Moa is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Moa.  If not, see <http://www.gnu.org/licenses/>.
# 
import os
import sys
import moa.template
import yaml

def tryDel(s,k):
    try:
        del s[k]
    except KeyError:
        pass
    
for fn, nm in moa.template.listAll():
    template = moa.template.Template(nm)
    raw = template.getRaw()    
    for f in raw.filesets:
        fs = raw.filesets[f]
        if not fs.has_key('pattern'):
            ext = fs.get('extension', '')
            glob = fs.get('glob', '*')
            dir = fs.get('dir', '*')
            if ext:
                pat = '%s/%s.%s' % (dir, glob, ext)
            else:
                pat = '%s/%s' % (dir, glob)
            tryDel(fs, 'extension')
            tryDel(fs, 'glob')
            tryDel(fs, 'dir')       
            fs['pattern'] = pat
    print nm
    
    #the following command would save the template again
    #template.saveRaw(raw)
    