#!/usr/bin/env python
# 
# Copyright 2009-2011, Mark Fiers, Plant & Food Research
# 
# This file is part of Moa - http://github.com/mfiers/Moa
# 
# Moa is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# 
# Moa is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Moa.  If not, see <http://www.gnu.org/licenses/>.
# 
import os
import sys
import moa.template
import yaml
import Yaco

for f in os.listdir(sys.argv[1]):
    if f[0] == '.': continue
    if f[-4:] != '.moa': continue
    ff = os.path.join(sys.argv[1], f)
    tmpl = Yaco.Yaco()
    tmpl.load(ff)
    if tmpl.parameters.has_key('title'):
        del tmpl.parameters['title']
        tmpl.save(ff)
