import os
import os.path
import sys

import wwwmoa.formats.xml as xml


def get_cgi_handler_path():
    return sys.executable # gets the pathname of the Python interpreter, which we will use for CGI

def get_install_static_path():
    return os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),"../../../../../static"))

def get_install_dynamic_path():
    return os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),"../../../../../dynamic"))

def escape_string(str):
    return str # [!] Placeholder

def get_env_file(home):
    return """<?xml version=\"1.0\"?>

<env>

    <!-- This configuration file was auto-generated by the WWWMoaLighty utility. -->

    <content path=\"""" + xml.fix_text(home) +"""\" />

</env>

"""

def get_env_file_path(port):
    return os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../../../etc/env/", str(port)+".xml"))

def port_has_env(port):
    return os.access(get_env_file_path(port), os.F_OK)

def get_config_file(port, home):
    return """

################################################################
###             CONFIGURATION FILE FOR lighttpd              ###
### This file was auto-generated by the WWWMoaLighty utility.###
### Generally, it is suggested that you not tinker with it   ###
### unless you are an advanced user.                         ###
################################################################


## User Specified Parameters ##

server.port=""" + str(port) + """


## Install Specific Information ##

server.document-root=\"""" + escape_string(get_install_static_path()) + """\"

cgi.assign=(
    \".py\" => \"""" + escape_string(get_cgi_handler_path()) +"""\"
)


## Required lighttpd Modules ##

server.modules=(
    \"mod_expire\",
    \"mod_cgi\",
    \"mod_rewrite\",
    \"mod_alias\"
)


## MIME Type Dictionary ##

mimetype.assign=(
    \".html\" => \"text/html\",
    \".htm\" => \"text/html\",
    \".txt\" => \"text/plain\",
    \".css\" => \"text/css\",
    \".js\" => \"text/javascript\",
    \".png\" => \"image/png\",
    \".gif\" => \"image/gif\",
    \".jpg\" => \"image/jpeg\",
    \".jpeg\" => \"image/jpeg\",
    \".pdf\" => \"application/pdf\",
    \".svg\" => \"image/svg+xml\"
)


## WWWMoa Specific Parameters ##

server.error-handler-404=\"/error-nf.html\"

index-file.names=(
    \"index.html\"
)

$HTTP[\"url\"]=~\"^/direct($|(/.*))\" {
    dir-listing.active=\"enable\"
}

url.rewrite-once=(
    \"^/index$\" => \"/index.html\",
    \"^/api$\" => \"/dynamic/api.py?request=\",
    \"^/api/(.*)$\" => \"/dynamic/api.py?request=$1\",
    \"^/hm$\" => \"/dynamic/hm.py?request=\",
    \"^/hm/(.*)$\" => \"/dynamic/hm.py?request=$1\",
    \"^/images/([^\\\\.]*)$\" => \"/images/$1.png\",
    \"^/styles/([^\\\\.]*)$\" => \"/styles/$1.css\",
    \"^/scripts/([^\\\\.]*)$\" => \"/scripts/$1.js\",
    \"^/about$\" => \"/dynamic/redir.py?target=about\",
    \"^/go/moa$\" => \"/dynamic/redir.py?target=moa\",
    \"^/go/firefox$\" => \"/dynamic/redir.py?target=firefox\",
    \"^/go/python$\" => \"/dynamic/redir.py?target=python\"
)

alias.url=(
    \"/dynamic\" => \""""+escape_string(get_install_dynamic_path())+"""\",
    \"/direct\" => \""""+escape_string(home)+"""\"
)

expire.url=(
    \"/\" => \"access 0 seconds\"
)

################################################################

"""

