import os
import sys

from moa.logger import l

def formatText(t):
    return " ".join(t.split())

def print_sys_message(str):
    l.info(formatText(str))

def print_error_message(str):
    l.error(formatText(str))

def print_fatal_error_message(str):
    l.critical(formatText(str))
    sys.exit(1)

def print_message(str):
    l.info(formatText(str)+os.linesep)

def do_main_prompt():
    return do_prompt(formatText("""Please enter a command.  For a
         listing of commands, please enter \"h\".  To exit, type \"q\"."""))

def do_prompt(instructions=""):
    r=raw_input(instructions+os.linesep+">> ")
    print 
    return r

def do_bool_prompt(instructions=""):
    while True:
        response=do_prompt(
            formatText(instructions +
                       " Please type 'y'/'yes' or 'n'/'no'."))

        if response=="y" or response=="yes":
            return True
        elif response=="n" or response=="no":
            return False

        print_message("Sorry, but you did not give one of the available answers.")

def do_int_prompt(instructions=""):
    while True:
        response=do_prompt(formatText(instructions))

        try:
            response_int=int(response)
            return response_int
        except:
            print_message("""Sorry, but you did not enter an integer,
                or something that could be converted to an integer.")

def show_help():

    print """
######################################################################

## WWWMoaLighty Help ##

You can use WWWMoaLighty like most other interactive command-line
utilities.  WWWMoaLighty actively manages the lighttpd processes
that are currently running.  Therefore, it remains open until all
of those processes have been terminated.

To control WWWMoaLighty while it is running, you can use the
following commands:

Using \"q\", \"quit\", or \"exit\" will terminate WWWMoaLighty. If
any lighttpd instances that were started with WWWMoaLighty are
still running, you will be prompted to terminate them as well.

Using \"h\", \"help\", or \"?\" will display this help message.

Using \"s\" or \"status\" will show the current lighttpd instances
being managed by WWWMoaLighty.

Using \"r\" or \"run\" will allow you to start up a new lighttpd
instance associated with WWWMoa.  You will be prompted about
what parameters to use for the new instance.

Using \"k\" or \"kill\" will allow you to shut down a currently
running lighttpd instance (given that it was started with
WWWMoaLighty).

Using \"l\" or \"log\" will allow you to see recent events that
you might be interested in.  Certain messages generated by
lighttpd will be shown.

######################################################################
"""

