blast_gff_source=blast.vs.sp.bacteria
blast_program=blastx
blast_db__cache=%DEPR/blastdb%
title=Blastp of the Glimmer3 genes vs the ecoli proteome
jid=Bdmb
owner=mf
blast_db=/home/mf/project/moa/demo/bacterial.annotation/05.databases/10.ecoli.proteome/20.blastdb/ecoli_proteome
project=demo_bacterial_annotation
blast_input_dir=../../10.gene.prediction/10.glimmer3/fasta/
blast_nohits=3
blast_gff_blasthit=T
