#!/usr/bin/env python

import os
import yaml
import moa.utils
import moa.template

from jinja2 import Template as jTemplate

jTemplateFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'template.rst.jinja2')
jTemplateIndexFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'template.index.rst.jinja2')

jT = jTemplate(open(jTemplateFile).read())
jTi = jTemplate(open(jTemplateIndexFile).read())

os.chdir(os.path.join(moa.utils.getMoaBase(), 'sphinx', 'templates'))

allTempates = []
for tfile, tname in moa.template.listAll():
    template = moa.template.Template(tfile)

    allTempates.append(tname)
    with open('%s.rst' % tname, 'w') as F:
        F.write(jT.render(template))

allTempates.sort()
with open('index.rst', 'w') as F:
    F.write(jTi.render({'templates' : allTempates}))

