#!/usr/bin/env python

import os
import sys
import yaml
import pkg_resources
import moa.utils
import moa.template

from jinja2 import Template as jTemplate

jt = pkg_resources.resource_string(
    'moa', 'data/jinja2/template.rst.jinja2')
jti = pkg_resources.resource_string(
    'moa', 'data/jinja2/template.index.rst.jinja2')

jT = jTemplate(jt)
jTi = jTemplate(jti)

_allTemplates = []
for provider, tfile in moa.template.templateList():
    print provider, tfile

    template = moa.template.getMoaFile(tfile)
    if not template:
        continue

    tname = template.moa_id
    assert(template.moa_id == tfile)


    _allTemplates.append(tname)
    with open('%s.rst' % tname, 'w') as F:
        F.write(jT.render(template))

_allTemplates.sort()
with open('index.rst', 'w') as F:
    F.write(jTi.render({'templates' : _allTemplates}))

