#!/usr/bin/env python

import os
import sys
import yaml
import moa.utils
import moa.template

from jinja2 import Template as jTemplate

jTemplateFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'template.rst.jinja2')
jTemplateIndexFile = os.path.join(
    moa.utils.getMoaBase(), 'lib', 'jinja2', 'template.index.rst.jinja2')

jT = jTemplate(open(jTemplateFile).read())
jTi = jTemplate(open(jTemplateIndexFile).read())

os.chdir(os.path.join(moa.utils.getMoaBase(), 'sphinx', 'templates'))

_allTemplates = []
for tfile in moa.template.templateList():
    print tfile
    template = moa.template.getMoaFile(tfile)    
    if not template: 
        continue

    tname = template.moa_id
    assert(template.moa_id == tfile)
    
    
    _allTemplates.append(tname)
    with open('%s.rst' % tname, 'w') as F:
        F.write(jT.render(template))

_allTemplates.sort()
with open('index.rst', 'w') as F:
    F.write(jTi.render({'templates' : _allTemplates}))

